qsrc/applet/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    

    url(r'^$', views.index , name='index'),
    url(r'^youtube', views.youtube , name='youtube'),
    url(r'^upload', views.data_upload , name='data_upload'),

]

qsrc/qsrc/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from applet import views
from realtime import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index', include('applet.urls')),
    url(r'^signin/', include('signin.urls')),
    url(r'^recent', views.firebase , name='firebase'),

]

qsrc/signin/urls.py
from django.conf.urls import url

from . import views

app_name = 'signin'

urlpatterns = [
    
    url(r'^registration/$',views.registration, name='registration'),
    url(r'^login/$',views.login, name='login'),
    url(r'^logout/$',views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^send/$', views.email,name='email'),



]

qsrc/applet/models.py
from django.db import models


class Urls(models.Model):
    sr_no = models.IntegerField(default=0,primary_key = True)
    prn = models.CharField(max_length=250, default= '2016BTEIT00025')
    links = models.CharField(max_length=2500, default= 'https://www.youtube.com/')
    count = models.IntegerField(default=0)
    primary_key = True

    def __str__(self):
     return str(self.sr_no)+ '---'+ self.prn

qsrc/realtime/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

qsrc/signin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from django.core.mail import EmailMessage

# Create your models here.

qsrc/signin/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class userform(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Username'}),
                             required=True,max_length=50)
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}),
                               required=True, max_length=50)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'}),
                               required=True, max_length=50)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'}),
                               required=True, max_length=50)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}),
                               required=True, max_length=50)
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}),
                               required=True, max_length=50)

    class Meta():
         model=User
         fields=['username','email','first_name','last_name','password']

qsrc/applet/views.py
import csv, io
from django.shortcuts import render, redirect, get_object_or_404
from .models import Urls
from django.contrib.auth.decorators import permission_required
from . models import Urls
from django.contrib import messages
import  re

@permission_required('admin.can_add_log_entry')
def data_upload(request):
    template = "applet/upload.html";

    if request.method == "GET":
        return render(request, template)
    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'This is not CSV file')

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        _, created = Urls.objects.update_or_create(
            sr_no = column[0],
            prn=column[1],
            links=column[2],
            count=column[3],
            
        )
    context = {}
    return render(request, template, context)


def index(request):
        template = 'applet/start.html'
        temp = []
        uname = request.user.username
        all_urls = Urls.objects.all()

        cnt=0
        for url in all_urls:
            if url.prn == uname:
                temp.append(url)
                cnt+=1
                if cnt == 5:
                    break


        context = {'all_urls' :all_urls ,'uname' : uname,'n' : range(5),'temp' : temp}
        return render(request,template,context)
	

def youtube(request):
    template = 'applet/youtube.html'
    temp = []
    uname = request.user.username
    all_urls = Urls.objects.all()


    for url in all_urls:

        if url.prn == uname:
            if re.match("https://www.youtube.com", str(url.links))!=None:
                temp.append(url)



    for i in temp:
        print(i)
    context = {'all_urls': all_urls, 'temp': temp}
    return render(request, template, context)

qsrc/realtime/views.py
import pyrebase
from django.shortcuts import render
from collections import OrderedDict

config = {
    'apiKey': "AIzaSyDWhUaHDhdC6R7J-rlddFaxqPjcGEqrENM",
    'authDomain': "quicksearch-177.firebaseapp.com",
    'databaseURL': "https://quicksearch-177.firebaseio.com",
    'projectId': "quicksearch-177",
    'storageBucket': "quicksearch-177.appspot.com",
    'messagingSenderId': "637425734410"
  };

firebase = pyrebase.initialize_app(config)
auth = firebase.auth()

database=firebase.database()

def firebase(request):

    """idtoken = request.session['uid']
    a = auth.get_account_info(idtoken)
    a = a['user/links']
    a = a[0]
    a = a['localId']"""

    uname = request.user.username
    data = database.child('user').child('links').get().val()
    data_l = list(data.items())

    data_list = []
    for x in data_l:
        d = {
            'pageId':x[1]['pageId'],
            'username': x[1]['useName']
        }
        if d['username']  == uname:
            data_list.append(d)


    context = {
        'data_list': data_list
    }

    return render(request,'recent.html',context)

qsrc/signin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.http import *
from django.contrib.auth.models import User
from django.contrib import auth,messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import logout,login
from applet import views
# Create your views here.
def registration(request):
    if request.method=='POST':
        form1=userform(request.POST)
        if form1.is_valid():
            username=form1.cleaned_data['username']
            first_name=form1.cleaned_data['first_name']
            last_name=form1.cleaned_data['last_name']
            email=form1.cleaned_data['email']
            password=form1.cleaned_data['password']
            User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)
            return HttpResponseRedirect('/upload/start')
    else:
        form1=userform()
    return render(request,'registration.html',{'frm':form1})

def login(request):
    '''if request.user.is_autheticated():
        return redirect('offerride/index.html')'''
    if request.method=="POST":
        username =request.POST['user']
        password=request.POST['pas']
        try:
            user=auth.authenticate(username=username,password=password)
            if user is not None:
                auth.login(request,user)
                return render(request,'welcome.html')
            else:
                messages.error(request,'Username and password did not match')
        except auth.ObjectNotExist:
            print("invalid user")
    return render(request,'login.html')


def logout(request):
    #logout(request)
    #return redirect('offerride/index.html')

    auth.logout(request)
    
    return render(request, 'login.html')

def admin_page(request):
    if not request.user.is_autheticated():
        return redirect('signin/login.html')

    return  render(request, 'offerride/index.html')


def profile(request):
    prof = User.objects.all()
    context={
        'profile': prof
    }
    return render(request,'profile.html',context)

def email(request):
    subject = 'ride confirmation'
    k = 'hello'
    email_from = settings.EMAIL_HOST_USER
    rel= 'ankichan1812@gmail.com'
    send_mail(subject, k, email_from, [rel],fail_silently=False)
    return render(request,'send.html')

qsrc/applet/templates/applet/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
   <title>QS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'cust.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  </head>
  <na background="{% static 'back.jpg' %}">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">QuickSearch</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'youtube' %}">Youtube Section</a></li>
          <li><a href="{% url 'firebase' %}">Recents</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'signin:registration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'signin:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <li><a href="{% url 'signin:logout' %}"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>

         {% block body %}
         {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

qsrc/applet/templates/applet/start.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
   <title>QS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'cust.css' %}"/>
      <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

  </head>
  <body background="{% static 'back.jpg' %}">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">QuickSearch</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'youtube' %}">Youtube Section</a></li>
          <li><a href="{% url 'firebase' %}">Recents</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'signin:registration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'signin:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <li><a href="{% url 'signin:logout' %}"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
    </nav>


    <div class="row">


              {% for url in temp %}

                    {% if uname == url.prn  %}
                      <div class="col-md-3">
                                    <div class="thumbnail">
                                      <a href="{{url.links}}">
                                        <img src="{% static 'qsearch.png' %}"  style="width:100%"  >
                                        <div class="caption">
                                          <P><strong>{{url.links}}</strong></P>
                                        </div>
                                      </a>
                                    </div>
                      </div>




                    {% endif %}

              {% endfor %}



    </div>











    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

qsrc/applet/templates/applet/upload.html
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<label>Upload Csv file</label>
	<input type="file" name="file">
	<button type="submit">Upload</button>
</form>

qsrc/applet/templates/applet/youtube.html
{% extends 'base.html' %}
{% load static %}
 {% block body %}
<h1>Youtube is here</h1>

 <div class="row">


                    {% for url in temp %}
                      <div class="col-md-3">
                                    <div class="thumbnail">
                                      <a href="{{url.links}}">
                                        <img src="{% static 'youtube.png' %}"  style="width:100%"  >
                                        <div class="caption">
                                          <P><strong>{{url.links}}</strong></P>
                                        </div>
                                      </a>
                                    </div>
                      </div>

                    {% endfor %}







    </div>

{% endblock %}

qsrc/realtime/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
   <title>QS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'cust.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  </head>
  <body background="{% static 'back.jpg' %}">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">QuickSearch</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'index' %}">Home</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'signin:registration' %}><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'signin:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <li><a href="{% url 'signin:logout' %}"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
    </nav>
    
         {% block body %}
         {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

qsrc/realtime/templates/recent.html
{% extends 'base.html' %}
{% load static %}

 {% block body %}

<h2 align="middle">RECENT</h2>

<!--<table>-->
  <!--<tr>-->
    <!--<th>Page ID</th>-->
  <!--<th>Username</th>-->
  <!--</tr>-->
 <!--{% for data in data_list %}-->
 <!--<tr>-->
  <!--<td>{{ data.pageId }}</td>-->
  <!--<td>{{ data.username }}</td>-->
 <!--</tr>-->
 <!--{% endfor %}-->
    <!---->
<!--</table>-->

     {% for data in data_list %}



                      <div class="col-md-4" align="middle" >
                                    <div class="thumbnail">
                                      <a href="{{data.pageId}}">
                                        <img src="{% static 'qsearch.png' %}"  style="width:50%"  >
                                        <div class="caption">
                                          <P  ><strong>links: {{data.pageId}}</strong></P>
                                        </div>
                                      </a>
                                    </div>
                      </div>



              {% endfor %}





{% endblock %}

qsrc/signin/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
   <title>QS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'cust.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  </head>
  <body >
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">QuickSearch</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'index' %}">Home</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'signin:registration' %}><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'signin:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <li><a href="{% url 'signin:logout' %}"> <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
    </nav>
    
         {% block body %}
         {% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

qsrc/signin/templates/login.html
{% extends 'base.html' %}

 {% block body %}
 <br><br><br>
    <div class="container">
        <div style="background-color:#122b40;color: white;font-size:22px" class="col-md-12">
            <b>User Login Page</b>
        </div>
        <div class="form-group col-md-12">
            {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
        </div>
        <div class="col-md-12">
            <form method="post" action="" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-md-offset-6 control-label">Username</label>
                    <div class=""col-md-12>
                        <input type="text" name="user" class="form-control" placeholder="Enter username">
                    </div>

                </div>
                <div class="form-group">
                    <label class="col-md-offset-6 control-label">Password</label>
                    <div class=""col-md-12>
                        <input type="password" name="pas" class="form-control" placeholder="Enter password">
                    </div>

                </div>
                <div class="col-md-offset-6">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>

        </form>
    </div>
</div>
<br><br><br>
{% endblock %}

qsrc/signin/templates/logout.html
{% extends 'base.html' %}

 {% block body %}
	 <div class="logout">
	 	<p>Successfully Loged out<a href="{% url 'offerride:index' %}"></a></p>
	 </div>

{% endblock %}

qsrc/signin/templates/profile.html
{% extends 'base.html' %}

{% block body %}

{% if user.is_authenticated %}




<div class="container" style="margin:100px;
     padding: 10;
     text-align: center">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">

                    <div class="col-sm-6 col-md-8">
                        <h1><i class="glyphicon glyphicon-user"></i>Username:    {{ user.username }}</h1>


                        <p>
                        <h2><i class="glyphicon glyphicon-star-empty"></i>First name:      {{ user.first_name }}</h2>
                            <br />
                        <h2><i class="glyphicon glyphicon-star-empty"></i>Last name:      {{ user.last_name }}</h2>
                             <br>
                            <h3><i class="glyphicon glyphicon-email"></i>Email:            {{ user.email }}</h3>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endif %}


{% endblock %}

qsrc/signin/templates/registration.html
{% extends 'base.html' %}

 {% block body %}
    <h1>
        Registration Form
    </h1>
    <div class="container">
        <div class="col-md-5">
            <form method="post" action="registration">
                {% csrf_token %}
                 {{ frm.as_p }}
            <button type="submit" class="signupbtn">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

qsrc/signin/templates/welcome.html
{% extends 'base.html' %}

{% block body %}
<h1>
    You are signed in
</h1>


{% endblock %}